WiFiManager.cpp, WiFiManager.h
Improved the support for Android and Chrome OS “Captive
Portal” detection. By returning a correct 204 status page when
/generate_204 is requested we prevent the device from disabling the
Wifi and roaming over to mobile data.
=> Improved support for Android and Chrome OS Captive Portal detection

WiFiManager.cpp, WiFiManager.h
This reduces the likelihood of a stack overflow when WifiManager is instantiated in setup(),
and lowers memory usage (after WiFi is connected) when it's instantiated globally.
=> Allocate the DNSServer and ESP8266WebServer on the heap at begin() time and free them when autoConnect() terminates.

WiFiManager.cpp, WiFiManager.h
As per [#1141](https://github.com/esp8266/Arduino/issues/1141), this will only work with the 2.0 esp8266 arduino libraries or current github.
Cheers,
John
=> Added password option to AP wifiManager.autoConnect("apname","password")

WiFiManager.cpp, WiFiManager.h
My hardware has a button to trigger configuration, so I needed a way to force the captive portal regardless of running configuration. So I added a third (defaulted) parameter to autoconnect(), namely forceAP. It is defaulted to false, for backward compatibility; but if it set to true, the captive portal is started without even attempting to connect with current SSID and password.
In the works, I have cleaned up some commented/unused code and changed connectWifi() to return the connection status, getting rid of temprary 's' varibles that were used to read status again right after a call to connectWifi().
=> Manually starting the configuration portal

WiFiManager.cpp, WiFiManager.h, examples/AutoConnectWithFeedback/AutoConnectWithFeedback.ino
To show the config portal SSID in the callback, a global reference to the WiFiManager object was needed. To solve this, a pointer to the WiFiManager object is now passed to the callback. The feedback example is edited accordingly.
This does break backward compatibility though, but saves memory.
=> Added parameter to callback

WiFiManager.h
Wifi passwords should not be in a clear text input field as browsers might cache them
=> Do not show clear text password in form input field

WiFiManager.cpp, examples/OnDemandConfigPortal/OnDemandConfigPortal.ino
Changed to make it work on ESP-01 boards.
It turn out that on ESP-01, the pin cannot be checked at setup as its only available pins, gpio0 and gpio2, are shared with the bootloader and **must** be kept HIGH at power-up.
- moved triggering of configuration portal into Arduino's loop() function
- changed pin from 4 to 0 (and made it  #define-able)
=> On-demand example now compatible with ESP-01 boards

library.json
Added missing comma that made the JSON invalid. Noticed this while trying to use the lib in platformio.
=> Fixed typo in  library.json

WiFiManager.h
If you have a long list of APs, the password field gets focuses on click, but this happens below the fold, this jumps to the form so you can see it. Added id to form instead of jumping to the #p field because it makes the input too close to the top of page, a well known issue of anchor links.
=> Jump to form for password entry

examples/AutoConnectWithStaticIP/AutoConnectWithStaticIP.ino
It seems that the first block of code *has* to be used in my case (using ESP8266 core v2.2.0).
Using the second block seems to cause a silent failure at runtime.
=> Improve comments for AutoConnectWithStaticIP example

examples/AutoConnectWithFSParameters/AutoConnectWithFSParameters.ino
'WiFiManagerParameter custom_mqtt_port' made consistent with declaration of 'mqtt_port'
=> Fix to allow 5 digit 'mqtt_port'

WiFiManager.cpp, WiFiManager.h
Allows to use startConfigPortal() without parameters. In this case the AP uses auto generated name ESP + ChipID just like autoConnect().
=> startConfigPortal() without any parameters

WiFiManager.cpp
array containing custom parameters is initialised at class
initialization time with a fixed value. When we later try to add more
parameters than the array allows we will now discard the offending
parameters and make a debug logging so the developer knows what's going
on.
Might be further improved as per this answer on StackOverflow:
http://stackoverflow.com/a/12271501
This would allow the array size to be specified at initialisation time,
and would give flexibility to the developer to decide how big the array
should be.
closes tzapu/WiFiManager#285
=> Don't add custom parameters if array size is exceeded

examples/AutoConnect/AutoConnect.ino
The (old?) function call is only done in a commented-out section, so the bug does not directly affect the functionality of the example code. But I encountered the error when I started playing with the various options of the WiFi Manager.
=> use setAPStaticIPConfig instead  of (old?) setAPConfig in first example

WiFiManager.cpp, WiFiManager.h
Fixed broken link:
Before: https://github.com/esp8266/Arduino/tree/esp8266/hardware/esp8266com/esp8266/libraries/DNSServer/examples/CaptivePortalAdvanced
After:  https://github.com/esp8266/Arduino/tree/master/libraries/DNSServer/examples/CaptivePortalAdvanced
=> Fix broken link

WiFiManager.cpp, WiFiManager.h
Patch to fix the issue: https://github.com/tzapu/WiFiManager/issues/392
-Change the <input ... length={l} ...> to maxlength (length isn't a valid HTML option).
-Increased the size of parLength[2] to parLength[5] so that the value of the length field can be up to 9999.
=> Fix for issue https://github.com/tzapu/WiFiManager/issues/392

WiFiManager.cpp
Without the suggested change, below error will occur during compilation (if parameter with custom "labelPlacement" was added): 
`undefined reference to WiFiManagerParameter::WiFiManagerParameter(char const*, char const*, char const*, int, char const*, int)`
=> Adding WiFiManagerParameter implementation with labelPlacement parameter

WiFiManager.cpp, WiFiManager.h
Previously a valid predefined static IP had to be passed before the
config page would show the IP, gateway and subnet fields. This did not
allow the config page to show 'optional' static IP fields.
Now a boolean can be passed to the autoConnect() function which will
specify whether the static IP fields should be shown or not.
When this boolean is true but no predefined values are passed and fields
are left blank in config page, wifiManager will revert to DHCP. This
allows user to choose between static IP or DHCP without changing code
For backwards compatibility we will show the static IP fields regardless of how the boolean is set.
=> Allow showing static IP config without predefined value

WiFiManager.cpp, WiFiManager.h
The WiFiManagerParameter constructor allocates _value via new but has no destructor to free  via delete.
=> WiFiManagerParameter allocates but never frees __value!

README.md, WiFiManager.cpp, WiFiManager.h
Dynamically allocate the _params array.  Existing no arg constructor uses the same default, 10, as it used to.  Added a second constructor that allows setting size.  Added Destructor that frees allocated _params.
=> use malloc/free for WiFiManagerParameter* array instead of hard coding.

WiFiManager.h
It took me a while to figure out that custom parameters don't work if there is a space in the id parameter. It's not particularly useful to make this work, so just document that it doesn't.
The reason it doesn't work: the client will use the id parameter as the name of the field in the HTTP GET request that goes back to the server. Spaces and other special characters will get encoded, so "Blynk token" becomes "Blynk+token". The server doesn't do any kind of decoding so it gets confused and thinks the parameter just isn't there.
=> Document that parameter id cannot contain spaces

WiFiManager.h
I think it's pretty useful to have this parameter customizable so that users can change it from outside if required (e.g platformio, make, etc). 
For example when using platformio I can set this in platformio.ini: 
**build_flags = -DWIFI_MANAGER_MAX_PARAMS=20**
This allows me to change  the value at compile time without modifying the library source code. I also provided the default value for it when not defined outside or somewhere else - you can see  that in the code changes that I want to propose.
This approach can be used for other defines in this library source code if desired/required.
Very nice work btw regarding this library - very useful. Thanks.
=> make WIFI_MANAGER_MAX_PARAMS customizable

WiFiManager.cpp, WiFiManager.h
add setEnableConfigPortal(boolean enable) - if false don't open config portal from autoConnect()
PR for this issue: https://github.com/tzapu/WiFiManager/issues/574
=> allow automatic config portal to be disabled

WiFiManager.cpp, strings_en.h
this will allow external portal on the network to send credentials via browser.
=>  add CORS headers

WiFiManager.cpp, WiFiManager.h
In https://github.com/esp8266/Arduino/pull/4889 the core was modified to disable WPS by default.  Its only enabled if NO_EXTRA_4K_HEAP is defined.  To enable you must re-run the board generator with --noextra4kheap. This adds #ifdef NO_EXTRA_4K_HEAP around WPS usage so it won't generate compiler errors.
=> disable wps by default, enable if its enabled in core

WiFiManager.cpp
https://github.com/tzapu/WiFiManager/pull/608 introduced a new header located in PROGMEM but did not use FPSTR() in its use causing crashes.
Exception Cause: 3  [LoadStoreError: Processor internal physical address or data error during load or store]
=> fix bad progmem access

WiFiManager.cpp
Had crashes in `doParamSave()`. 
Changed to use `server.hasParam()` instead of checking `server.arg()` for NULL, it returns a `String` not a pointer.
Don't use `.c_str()` when its being assigned to a `String`. I think using `.c_str()` on `String` that are transient is probably not safe.
=> Fix crasahes in doParamSave() &  WiFiManagerParameter::setValue

WiFiManager.h, examples/CustomParamsWithConfig/CustomParamsWithConfig.ino
Little feature to make possible children classes for easy custom parameters.
Example: https://github.com/dontsovcmc/waterius/blob/master/ESP8266/src/setup_ap.h
=> WiFiManagerParameter init() to protected from private

WiFiManager.cpp, WiFiManager.h
I figured out, that there is no check on the hardware plattform, which is currently selected.
There are serval plattforms, which does not compile, i suggest adding a if defined check to the preprocessor.
Why is this useful?
I've a multi plattform Project. I used two seprerate source code projects in the past, but now i want to merge them. When i try to compile my project with an AVR Board, it fails, because it trys to compile the wifi lib but doesn't find serval used libs.
-added define that checks on esp32 or esp8266. If another hardware is selectec, then do not try to compile this code.
=> wifimanager.cpp / wifimanager.h

WiFiManager.cpp
i wrapped to int() function, because cannot match on css because the incoming data is decimal
=> signal class value has been wrapped to int()

WiFiManager.cpp, WiFiManager.h
ref: https://github.com/esp8266/Arduino/pull/6413
=> hotfix: rename internal HTTP_HEAD to HTTP_HEADER 

WiFiManager.cpp
Fixed Waiting for connection result with time out issue.
If the ESP connection to wifi network on first try was unsuccess, there was no another try regardless timeout is how far away. This modification fixes the issue.
=> Fixed: Waiting for connection result with time out issue

.github/ISSUE_TEMPLATE.md, WiFiManager.cpp, examples/AutoConnectWithFSParameters/AutoConnectWithFSParameters.ino, examples/AutoConnectWithFSParametersAndCustomIP/AutoConnectWithFSParametersAndCustomIP.ino, library.json, library.properties
This is relates to the ArduinoJson 5 / 6 changes.
I took what @bigjohnson did in a502456 and just added a #define UseJsonV6 option that can be commented out if you want to use ArduinoJsonV5.
Tested on ArduinoJson V 5.13 and ArduinoJson V 6.13 (Latest as at 14/01/2020)
This also links to #654 and #812
=> Fix ArduinoJson (Using ARDUINOJSON_VERSION_MAJOR)

README.md
I think it's better to add Note about DNS if somebody want to use static IP and syncronize time (NTP) or request web servers by hostname in source code.
=> Readme: fill DNS server if setSTAStaticIPConfig

WiFiManager.cpp
This fixes an unused variable warning as the call to
heap_caps_get_free_size() is not required.
Tests:
- Enable debug mode and verify free heap and ESP SDK
version are correctly displayed
- Cross check with the free heap reported via the captive
portal info page
=> Fix warning in WiFiManager::debugPlatformInfo for ESP32

WiFiManager.cpp
As written, the way constrain is used has no effect/unintended effect and will generate the following warnings:
```
warning: second operand of conditional expression has no effect [-Wunused-value]
warning: third operand of conditional expression has no effect [-Wunused-value]
```
This change addresses those warnings and corrects the behavior.
=> Use constrain properly

WiFiManager.cpp
Fix [commit](https://github.com/tzapu/WiFiManager/commit/e071e3ad8fb799044589643b1f355ef750485599). The library is not assembled under esp8266.
=> Fix. The library is not assembled under ESP8266

WiFiManager.h
because sometimes you need to know :p !!!!!
=> adding WifiManager::isConfigPortalActive() abd WifiManager::isWebPortalActive()

WiFiManager.cpp
DEBUG_WM(DEBUG_VERBOSE,F("<- HTTP Wifi save "));  while it's obviously Params instead of Wifi
=> fix  debug message in WiFiManager::handleParamSave

WiFiManager.cpp, WiFiManager.h
Enhancement: It should be okay to invoke getID() and getValue() in a
const instance of the WiFiManagerParameter class.
For usage example, see: https://github.com/flavio-fernandes/persistWifiSetting/commit/135adb1c7e436db1ed92ccd5eb522b9ae418b216
=> trivial: WiFiManagerParameter get accessors should work on const

.github/workflows/examples_esp8266.yml
Hi, I've added compilation of all examples, so you would see if something would fail here in Github.
There are few tests failing - not sure what version of ArduinoJson it should be using - latest 6 fails with missing methods.
Please squash while merging.
=> Added Github Action to Compile Examples on ESP8266

WiFiManager.cpp, WiFiManager.h
Add a callback to be used before the OTA update. The OTA update sometimes can be corrupted because of timer interrupts. The idea is to have a method "setPreOtaUpdateCallback()" to set a user-defined callback. This callback is called just before uploading the new firmware so that the user can disable all the interrupts that may corrupt the OTA update.
=> Add a callback for OTA update

WiFiManager.cpp
Notice that if we set the _setConfigPortalTimeout( **60** )_ and _setConfigPortalBlocking( **false** )_ we got the first message 
"*wm:[2] Portal Timeout In 60 seconds" but nothing after that. 
This PR is calling the handling for the timeout inside of the process function, in other to utilize the timeout mechanism 
Tested with ESP8266
=> Enable Portal Timeout in not Blocking Portal

WiFiManager.cpp
Comparing it to NULL raises operation overload.
=> Both infoids and _ap_password are intialized by check time.

WiFiManager.cpp, WiFiManager.h
This is to address https://github.com/tzapu/WiFiManager/issues/1341 and https://github.com/tzapu/WiFiManager/issues/1050
These changes should have no affect on the functionality except to slightly simplify the class, and add the additional copy/move functions.
Feel free to use this as a starting point if there are stylistic inconsistencies.
=> Move WiFiManagerParameter to use a smart pointer and add copy/move constructors

WiFiManager.h
This change closes #1381 by not attempting to include core_version.h (which will not exist if the platform has been fully released).
=> Output "Unknown" if Arduino/ESP-IDF version is unknown

strings_en.h
From  "v1.0.11-beta" to "v2.0.11-beta"
I think the major version was forgotten to be updated.
=> WM_VERSION_STR correction (used in About section)

WiFiManager.cpp
This should allow SSIDs that contain single quotes to populate data-ssid correctly. Without this patch, clicking on an SSID containing a single quote will either:
* Not use the whole SSID, in cases where there's text before the quote:
`foo'bar` will appear in the SSID box as just `foo`
* Fall back to innerText, in cases where the quote is the first character in the SSID:
`'); DROP TABLE WIFI; --` will appear in the SSID box as a version that has spaces converted to non-breaking spaces, causing the connection to eventually fail with WL_NO_SSID_AVAIL.
Fixes #1412
=> Escape single quotes in htmlEntities()

WiFiManager.cpp, WiFiManager.h
WifiManager does not use any `Stream` functionality for `_debugPort`; change the declaration of `_debugPort` so that it is more easily used by other implementations.
Personally, I use a ring buffer that implements Print but not Stream for reading.
=> Change Stream to Print

WiFiManager.cpp
Avoid constructing two String objects and adding them together. Just concatenate c-strings.
=> Avoid String addition when dealing with compile time

WiFiManager.cpp
This pull request replaces the use of `esp_wifi_set_country()` with `esp_wifi_set_country_code()` for ESP32 in order to both solve a crash under Arduino 2.x and remove the requirement to independently maintain country-specific channel settings. In testing on my end, this solves the crash seen in #1309 .
One thing of note - I think that `esp_wifi_set_country_code()` was only added with the later versions of esp-idf added when Arduino 2.x was released -- I'm not sure if you intend to continue to support the earlier framework, but if you do then some conditional compilation logic may be needed here.
=> Use esp_wifi_set_country_code for ESP32

.github/workflows/compile_examples.yaml
This fixes the "compile examples" GitHub action in order to use the incoming code rather than the existing master at tzapu/WiFiManager
This fixes #1472
=> Change test action to install from local directory

CMakeLists.txt
Enables support for WifiManager as an ESP-IDF component.  ESP-IDF is a popular development framework for ESP32 chips.
This file is based on the CMakeLists.txt file from the popular Adafruit-GFX-Library library.
=> Support for WifiManager as ESP-IDF component

WiFiManager.cpp, WiFiManager.h, strings_en.h
Hi,
I'm currently working in an environment where I have to connect the ESP32 to a WPA2 Enterprise network protected with PEAP. Given the nature of such a network, the credentials are used for more than just WiFi. I was hence uncomfortable with configuring my username & password directly on a sketch that I would be sharing, so I decided to use WiFiManager.
The PR contains some code to get WiFiManager working with PEAP-protected networks. Is implementing support for WPA2 Enterprise networks currently on the roadmap?
I had to use my own NVS storage, as it seems like the ESP32 framework doesn't automatically save credentials for anything outside of a typical SSID & Password combo.
=> WPA2 Enterprise PEAP support

WiFiManager.h
Allows to extend WiFiManger and parameter classes so you can customize it.
Making the internal variables/methods protected instead of private should not change any existing behavior.
=> Allow subclassing

README.md
Hi, thanks for the great library. Here's a tiny contribution in return. I tested on ESP32-S3 so the readme now has the shield for ESP32-S3. And I fixed the Release shield from clicking to the image page. -Frank
=> Wifi manager frank cohen

.github/workflows/compile_examples.yaml, .github/workflows/compile_library.yml
This PR refines the caching strategy used in the `Compile Library` GitHub Actions workflow by making cache keys board-specific. Previously, caches for `pip` and `PlatformIO` were shared across all board configurations, which could lead to cache conflicts or inefficiencies. Now, each board (e.g., `nodemcuv2`, `lolin32`) has its own unique cache, improving cache hits and reducing build times.
- Modified cache keys for `pip` and `PlatformIO` to incorporate the board matrix value.
- This change ensures better cache management when multiple boards are being built, preventing cache collisions.
This change improves the efficiency of the CI/CD pipeline by ensuring that the cache is appropriately scoped for each board, optimizing build times for different configurations.
=> Enhance cache strategy with board-specific cache keys

.github/workflows/compile_examples.yaml
- Aligned cache keys for `esp8266` and `esp32` jobs to use `${{ github.ref }}` in the key, improving cache consistency across branches.
- Fixed a typo in the `Install 3rd party dependencies` step (`dependecies` → `dependencies`).
These changes ensure more efficient caching and fix a minor issue in the workflow.
=> Fix cache key inconsistency and typo in 'Compile examples' GitHub Actions workflow

WiFiManager.cpp, WiFiManager.h, wm_consts_en.h, wm_consts_fr.h
This PR adds classes to the body element for each individual page, so that it's easier to style pages differently:
| Title (en)        | Route      | Class   |
|-------------------|------------|---------|
| WiFiManager       | /          | home    |
| Config ESP        | /wifi      | wifi    |
| Credentials saved | /wifisave  | wifi    |
| Info              | /info      | info    |
| Setup             | /param     | param   |
| Setup saved       | /paramsave | param   |
| Restart           | /restart   | restart |
| Exit              | /exit      | exit    |
| Close             | /close     | close   |
| Erase             | /erase     | erase   |
| Update            | /update    | update  |
| options           | /u         | update  |
This is accomplished by modifying the `getHTTPHead()` …
=> Add CSS body classes for each page

WiFiManager.h
The esp8266/Arduino v3+ now utilizes gcc10's C++17, which includes std::byte, making Arduino's byte incompatible with using namespace std, yielding the error "Reference to 'byte' is ambiguous."
to fix this I replaced `byte` with the standard type `uint8_t`
=> Replace deprecated type

WiFiManager.cpp
Compiler warning : format '%lu' expects argument of type 'long unsigned int', but argument 3 has type 'uint32_t' 
The compiler warning arises because the format specifier %lu expects a long unsigned int, but the variable free is of type uint32_t (which is typically unsigned int). The ESP32, part of the Espressif32 family, typically defines uint32_t as unsigned int, so using the %u format specifier is appropriate.
=> Fix compilation warning when compiling with -Wformat flag
