tzapu/WiFiManager

- WiFiManager.cpp
Would be nice to print IP address to console.
BTW Nice library - thanks ;)
> Show local IP address in STA mode

- keywords.txt
to standardize the library and appear in Library Manager
> add keywords.txt

- library.properties
to standardize the library and appear in Library Manager
> add library.properties

- library.json
to standardize the library and appear in Library Manager
> add library.json

- WiFiManager.cpp
- WiFiManager.h
- examples/AutoConnectParametersWithTimeout/AutoConnectParametersWithTimeout.ino
> I saw some comments on the plans to add custom parameters.
> Here I'm contributing a working implementation, it uses the EEPROM.
> Keep the nice work on this library!
> Just my 2 cents.
i hope you don't mind, i created a new pull request on a secondary branch so i can play with it a bit without disrupting the main branch.
absolutely love what you ve done, thank you
> allow custom parameters

- WiFiManager.cpp
- WiFiManager.h
I wanted to use the config portal SSID in the callback, so I can direct a user to that SSID. I added getConfigPortalSSID() to enable that.
> Adding a method to get the config portal SSID

- README.md
- WiFiManager.cpp
- WiFiManager.h
As a  side note, I think we should give _ip etc more explicit names to avoid confusion.
> Adding Static IP Support

- WifiManager
* This library in Web Registry: http://platformio.org/#!/lib/show/567/WifiManager
* Specification: [library.json](http://docs.platformio.org/en/latest/librarymanager/config.html)
* Library Manager:  http://docs.platformio.org/en/latest/librarymanager/index.html
> @PlatformIO Library Registry manifest file

- WiFiManager.cpp
- WiFiManager.h
> Remove duplicate aps

- extras/WiFiManager.template.html
The quotes are missing, this create an issue
> Quotes are missing creating issues.

- README.md
Improve wishlist readability by replacing strikeout to checkboxes.
> Improve wishlist in README

- WiFiManager.cpp
- WiFiManager.h
forgot to switch my dev to origin, still pushing to fork , oops
> added some esp abstraction to make ports easier

- WiFiManager.cpp
Place remaining debug messages into Flash using F() and declare a few other strings with F()
> Move more strings to FLASH to free up RAM

- WiFiManager.cpp
- WiFiManager.h
- strings_en.h
git fetch id:pr560
dos2unix *.cpp *.h
git commit newline fix
git rebase -i HEAD~2
pick
squash
commit
pushed
> Added Custom DNS, fix newlines

- WiFiManager.cpp
Swapping enableAP and softAPConfig for static IP STA
> Swapping enableAP and softAPConfig

- WiFiManager.h
https://github.com/tzapu/WiFiManager/issues/644
> issuu #644 add utf-8 charset to head

- WiFiManager.cpp
- WiFiManager.h
hi @tzapu @tablatronix previously I can't found listener before save wifi or params. i have made for it and very helpful. I use for disable other process can make stuck or reset ESP, enabled again when finish process.. and finally smooth process without ESP reset.
thx
> add callback before save config wifi or params

- WiFiManager.h
https://github.com/tzapu/WiFiManager/pull/687
> separate charset UTF-8 and viewport meta

- README.md
One less thing for you guys to document!
> Add PlatformIO installation docs

- extras/WiFiManager.template.html
- extras/test.html
- strings_en.h
Fixes a tiny error in the label strings Acccess -> Access
> Fix "Acccess" typo

- WiFiManager.cpp
This is probably a left over from debugging, can we remove or at least move it to a DEBUG_WM
> Silence debug output

- strings_en.h
show/hide wifi password during input
> Update strings_en.h -> show/hide wifi password in form

- README.md
Added links for compile pages (library/examples) + expressif product pages
> Added links in readme file

- WiFiManager.cpp
- WiFiManager.h
This is PR for add config portal timeout callback for handle config portal timeout.
For Resolve: #1496
> feat(callback): add config portal timeout callback.

- WiFiManager.cpp
- WiFiManager.h
This PR adds HTTP Digest Authentication (or revives the dead feature). May not work with some Android native webview browsers (Upon tapping "Sign in to network" notifications).
> Add HTTP Digest Authentication

- wm_consts_fr.h
- wm_strings_fr.h
Proposal of French translation
> FR Translation

- WiFiManager.cpp
> Force remove DNS input from Captive portal issue #1733

- WiFiManager.cpp
> Patch race condition with DNS on portal shutdown
